### PR TITLE
Create a zh_CN language file

### PR DESCRIPTION
**Pull request by TartaricAcid**
I add a Chinese language file for the mod.

### CODE REVIEW

**Comment by hanakocz** [comment]
Ok, thx, can you please keep an eye on changes in lang file and keep it updated? I can't speak chinese so cannot do it myself. :) Thx

**Comment by TartaricAcid** [comment]
of course, and I hope the mod have a better development.

**Comment by hanakocz** [comment]
@TartaricAcid the new build is out, with this lang file included. However new two or three items don't have transation, so if you would be able to give them proper translation, I can update those for next version.

**Comment by TartaricAcid** [comment]
thanks for your remind.

**Pull request merged**
